# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-06-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_editor_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={},
        ),
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=3, upload_to='articles/'),
            preserve_default=False,
        ),
    ]
